@startuml usecases

set separator ::

skinparam actorStyle awesome

left to right direction

actor Bruger as bruger

package Spotify_Klient {
    usecase "Log in" as login

    usecase "Afspil musik" as afspil
    usecase "Afspil podcast" as afspilPodcast

    note "Dette skridt er det vigtigste i systemet, det er her \nbrugeren får mulighed til at afspille deres indhold" as n4

    usecase "Få anbefalinger" as anbefal

    usecase "Indhold fra dit biblotek" as biblotek

    note "De 3 funktioner i denne kolone er alle relateret \ntil at finde, eller interegere med musik" as n2

    package Indhold as indhold {
        usecase "Sange" as sang
        usecase "Albumer" as album
        usecase "Kunstnerer" as kunstner
        usecase "Playlister" as playliste
        usecase "Podcasts" as podcast

        note "Indholdet i denne del er alt der som spotify \nkan anbefale eller du kan gemme i din biblotek" as n1
    }

    usecase "Sang kø" as kø

    usecase "Log ud" as logud
    usecase "Åben profil" as profil

    note "Proceserne i denne kolone styre alle sammen \nbrugerens tilgang til resten af programmet" as n3
}

login -up-> bruger : Error: Forkert brugernavn \neller kodeord
bruger --> login : Log på forsøg
login --> kø

login --> biblotek
biblotek -down-> indhold

album --> sang : Indeholder
kunstner -down-> album : Indeholder
kunstner -down-> sang : Indeholder
playliste -right-> sang : Indeholder

sang -down-> afspil
kø --> afspil

podcast -down-> afspilPodcast

login --> anbefal
anbefal -down-> indhold

login -left-> logud
login -right-> profil

logud --> bruger

afspil -[hidden] afspilPodcast
album -[hidden]-> podcast

kunstner -[hidden]-> n1
n1 -[hidden]-> podcast

kø -[hidden] n2
n2 -[hidden] biblotek

n3 -[hidden] profil

n4 -[hidden] afspilPodcast

@enduml