@startuml usecases

set separator ::

skinparam actorStyle awesome

left to right direction

actor Bruger as bruger

package Spotify_Klient {
    usecase "Spotify" as main

    usecase "Afspil musik" as afspil
    usecase "Afspil podcast" as afspilPodcast

    note "Dette skridt er det vigtigste i systemet, det er her \nbrugeren får mulighed til at afspille deres indhold" as n4

    usecase "Få anbefalinger" as anbefal

    usecase "Indhold fra dit biblotek" as biblotek

    note "De 3 funktioner i denne kolone er alle relateret \ntil at finde, eller interegere med musik" as n2

    package Indhold as indhold {
        usecase "Sange" as sang
        usecase "Albumer" as album
        usecase "Kunstnerer" as kunstner
        usecase "Playlister" as playliste
        usecase "Podcasts" as podcast

        note "Indholdet i denne del er alt der som spotify \nkan anbefale eller du kan gemme i din biblotek" as n1
    }

    usecase "Indhold sang kø" as kø

    usecase "Log ud" as logud
    usecase "Åben profil" as profil

    note "Proceserne i denne kolone styre alle sammen \nbrugerens tilgang til resten af programmet" as n3
}

main -up-> bruger : Hvis fejlet main
bruger --> main : Log på forsøg
main --> kø

main --> biblotek
biblotek -down-> indhold

album --> sang
kunstner -down-> album
kunstner -down-> sang
playliste -right-> sang

sang -down-> afspil
kø --> afspil

podcast -down-> afspilPodcast

main --> anbefal
anbefal -down-> indhold

main -left-> logud
main -right-> profil

logud --> bruger

afspil -[hidden] afspilPodcast
album -[hidden]-> podcast

kunstner -[hidden]-> n1
n1 -[hidden]-> podcast

kø -[hidden] n2
n2 -[hidden] biblotek

n3 -[hidden] profil

n4 -[hidden] afspilPodcast

@enduml